project_id = "qasrsadhebdlwgxffkya"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true
port = 54323
ip_version = "dual"

[studio]
enabled = true
port = 54324
api_url = "http://127.0.0.1:54321"

[inbucket]
enabled = true
port = 54325
smtp_port = 54326
pop3_port = 54327

[storage]
enabled = true
file_size_limit = "50MiB"
image_transformation = {enabled = true}

[auth]
enabled = true
site_url = "http://127.0.0.1:3000"
additional_redirect_urls = ["https://qasrsadhebdlwgxffkya.supabase.co"]
jwt_expiry = 3600
enable_manual_linking = false

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[edge_runtime]
enabled = true
ip_version = "dual"

[functions.create-payment]
verify_jwt = true

[functions.handle-payment-success]
verify_jwt = true

[functions.generate-covers]
verify_jwt = true

[functions.verify-payment]
verify_jwt = true

[functions.upscale-cover]
verify_jwt = true

[functions.remix-cover]
verify_jwt = true